### ISSUE TITLE
vkGetRandROutputDisplayEXT doesn't return VK_INCOMPLETE when it should

### ISSUE THREAD

**Issue by JacobHeAMD** [GPUOpen-Drivers/pal#38]
@ kleinerm report it on https://github.com/GPUOpen-Drivers/pal/pull/37

Additionally there is a bug in the XGL component which prevents vkGetRandROutputDisplayEXT() from returning VK_INCOMPLETE as it should if it encounters this pal error.

Here:

https://github.com/GPUOpen-Drivers/xgl/blob/2c44bbc7b58efba12c501f71f5b268f83c1bdad5/icd/api/vk_physical_device.cpp#L3808

Inside the error handling clause of the if statement, instead of
result = VK_INCOMPLETE;
we have
VKResult result = VK_INCOMPLETE;

So in case of error, result is assigned inside the local scope, and then goes out of scope when leaving that branch, and return result actually returns VK_SUCCESS.

However, i actually stumbled over these bugs while i was trying to figure out why vkGetRandROutputDisplayEXT() works unreliably in the officially released amdvlk drivers.

Testing against the different released drivers on Ubuntu 19.10, depending on the driver release, either vkGetRandROutputDisplayEXT() works as expected, or fails and returns VK_SUCCESS, but also returns a NULL VkDisplayKHR handle. I'm not sure if this is because the driver is only officially supported for Ubuntu 18.04 LTS, or if something is wrong in your release process. I can't reproduce the failure with my own self-built driver checked out from your Git repos, so was unable to track down the cause.

E.g., these releases worked on Ubuntu 19.10:

amvlk PRO 1.1.129 from the amdgpu-pro driver package.
amdvlk 2019.Q4-3
And one of the 2020.Q1-x drivers also worked, can't remember which one atm.

These fail:

2019-Q4-5
2020-Q1-1

And the latest 2020-Q2-1 driver fails again.

**Comment by kleinerm** [comment]
To move this along, i created a pull request against XGL with the proprosed and successfully tested fix:

https://github.com/GPUOpen-Drivers/xgl/pull/56

**Comment by JacobHeAMD** [comment]
Thank you! @kleinerm

**Comment by kleinerm** [comment]
I spent a lot more time scratching my head about the failure of vkGetRandROutputDisplayEXT() with the latest 2020-Q2-2 drivers. I attached gdb, setting breakpoints on dlopen() to see which libraries get loaded, and found out that the dlopen calls corresponding to the Dri3Loader init never happen. I also used xtrace to trace the X11 requests made to the server, and found out that the xcb_intern_atom() request for the CONNECTOR_ID never happens. This suggests that the PAL code for mapping RandR outputs never executes.

My best hunch about why would be that the #defines needed for X11 RandR output leasing are not set and so this code is essentially a no-operation in the released driver!

If i build the amdvlk driver myself, with a checkout of the master or dev branches from your repositories, ie. using repo tool to get the source tress, then following the cmake and make instructions, i get a driver that is supposedly built from the same source code as the official driver. This self built driver works perfectly fine wrt. output leasing, as tested on Ubuntu 19.10 and 20.04-LTS.

Now here's the catch. Various macros in XGL and PAL needed to enable this are only defined iff the the driver is built on a machine which has xcb-proto version 1.13 or later and thereby defines RandR version as >= 1.16. On my Ubuntu 19.10 system, this is the case. I just checked though that Ubuntu 16.04 ships a xcb proto version of 1.11 only and thereby does not support RandR 1.16 or later, so iff your release drivers are built on a standard Ubuntu 16.04 LTS system, support for vkGetRandROutputDisplayEXT and vkAcquireXlibDisplay() would be missing!

So my question: What build system do you use for the officially released amdvlk drivers? Could a build system of at least Ubuntu 18.04 LTS be used to potentially fix this problem?

**Comment by kleinerm** [comment]
To answer my own question: I hacked the relevant xcb/randr.h header file on my build system to only expose compile time support for RandR version 1.5, then rebuilt the driver and the resulting driver shows exactly the same failures with exactly the same symptoms as the AMD released amdvlk drivers. Reverting the header file back to RandR 1.6 and rebuilding results in a nicely working driver again. So lack of RandR 1.6 support on your build system is likely the reason for the brokeness of the released drivers and this could be fixed by providing a released driver built on Ubuntu 18.04-LTS or later, whose xcb / xcb-proto development files seem to be up-to-date enough.

The strange thing is that, although your Ubuntu build removes support for the VK_EXT_ACQUIRE_XLIB_DISPLAY extension, the extension is still exposed by the driver as supported, the entry points for vkGetRandROutputDisplayEXT() and vkAcquireXlibDisplay() are defined and callable, but they are no-ops. vkAcquireXlibDisplay() at least returns an error code, but vkGetRandROutputDisplayEXT() no-ops while returning VK_SUCCESS.

Given that working direct display mode is very important for video games, VR / AR applications, HDR applications and neuroscience/medical research applications, could you provide a suitable build of amdvlk? Should i repost this request against the AMDVLK repo? Please advise.

**Comment by kleinerm** [comment]
Ok, it seems as if this problem is now solved with the 2020-Q2-3 driver. Quick test shows that output leasing finally works. Looking at the recent AMDVLK commits, upgrading to a build system of Ubuntu 18.04, RandR 1.6 should be supported and output leasing should be enabled at compile time.

So this isse can be closed.

**Comment by kleinerm** [comment]
Ok, i was too optimistic in my statement. Filed a new issue against AMDVLK:
https://github.com/GPUOpen-Drivers/AMDVLK/issues/164

**Comment by kleinerm** [comment]
Fixed in the 2020-Q2-5 driver. This issue can be closed. Thanks.
