### ISSUE TITLE
pal assumes the processor is an x86

### ISSUE THREAD

**Issue by berolinux** [GPUOpen-Drivers/pal#57]
Parts of pal use x86 specific headers and instructions (e.g. CpuId stuff in palSysUtil.h, sysUtil.cpp, lnxSysUtil.cpp).
AMD GPUs are used in other machines (aarch64, RISC-V) as well; works fine with Mesa drivers. AMDVLK currently can't be compiled for those machines.

**Comment by JakeMerdichAMD** [comment]
That one's already on my backlog. Glad to know folks in the community are interested too! I'll get that out in the coming weeks.

Be aware, this does not imply official ARM/RV64 support, mainly because we don't have anything set up to test or debug it. I will be happy get build issues fixed, advise, and take PRs, though.

**Comment by JakeMerdichAMD** [comment]
Fixed internally. I'll close this out when it reaches the public.

**Comment by berolinux** [comment]
Great, thanks. Any chance you can share the patch? The OpenMandriva 4.2 release is about to happen, and I'd like to have a proper fix for this in (in place of the crappy hack I've put in in the mean time, https://github.com/OpenMandrivaAssociation/AMDVLK/blob/master/amdvlk-nonx86.patch )

**Comment by JakeMerdichAMD** [comment]
Here you go: https://github.com/JakeMerdichAMD/pal/commit/c789d6ef3ea6f90ce2fb0e1b0f8f7a8586b23854.patch

**Comment by JakeMerdichAMD** [comment]
Fixed via 5262df4eae038624c412904f0a250b66db92194b
