### ISSUE TITLE
How to build on Windows use vs2019?

### ISSUE THREAD

**Issue by Jaylon2022** [GPUOpen-Drivers/pal#86]
**Hello, how to compile using vs2019 on windows? I used cmake to generate the vs2019 project and reported the following error:**

CMake Error at cmake/PalVersionHelper.cmake:91 (message):
  PAL_CLIENT_INTERFACE_MAJOR_VERSION not set.  Defaulting to -1.
Call Stack (most recent call first):
  cmake/PalBuildParameters.cmake:34 (pal_bp)
  CMakeLists.txt:30 (include)

**how will i deal with it?
thanks**

**Comment by jpr42** [comment]
In order to use pal, clients have to set a variety of variables before calling `add_subdirectory`.

Here is where vulkan sets [PAL_CLIENT_INTERFACE_MAJOR_VERSION](https://github.com/GPUOpen-Drivers/xgl/blob/a3967ec7a8c362c081d541686c8bd8c60b2d89c6/cmake/XglOverrides.cmake#L137) before absorbing pal.

Pal isn't meant to be built standalone and must be built as part of a larger graphics driver. Pal currently isn't designed to be built standalone like a typical CMake library. This is due to historical reasons, and internal development reasons.

Please refer to AMDVLK for complete build instructions and supported platforms:
https://github.com/GPUOpen-Drivers/AMDVLK
