### ISSUE TITLE
Add zwp_linux_dmabuf_v1 support to Wayland WSI

### ISSUE THREAD

**Issue by i509VCB** [GPUOpen-Drivers/pal#96]
I noticed that the Wayland WSI currently uses the old wl_drm. Most compositor implementations better support the newer zwp_linux_dmabuf_v1 protocol. wl_drm might not necessarily be available if the compositor uses Vulkan for rendering.

**Comment by JakeMerdichAMD** [comment]
I've added this new wayland protocol to our backlog (it has other benefits like improved startup time too). The crash you linked does not quite seem like a bug on our end, though. Instead of using modifiers, the `wl_drm` protocol uses vendor-specific metadata paths just like X11 and only uses the format for the vendor-neutral part of the format (eg RGBA8888 or RGB565).

**Comment by i509VCB** [comment]
Yeah the wl_drm issue is one with smithay and cosmic, but the newer protocol is appreciated.

**Comment by jinjianrong** [comment]
Tracked with SWDEV-440638  internally

**Comment by jinjianrong** [comment]
Done in 2024.Q4.1 release
